# -*- coding: utf-8 -*-
"""zoo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F39qVRSRZafxZP2TYmYcT40PSmO-JP1o
"""

def hours():
  print("Open 9-5 Daily")